config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do
  resources :cost_centers


  resources :cash_receipts


  resources :suppliers


  resources :spares


  resources :labors


  resources :work_orders


  resources :mechanicals


  resources :sale_by_cost_centers


  resources :form_of_payments


  resources :banks


  resources :shoppings


  resources :history_of_vehicles


  resources :account_receivables


  resources :account_payables


  resources :customers


  resources :profiles


  resources :documents


  authenticated :user do
    root :to => 'home#admin'
  end
  root :to => "home#index"
  devise_for :users
  resources :users

  

end

app/models/history_of_vehicle.rb
class HistoryOfVehicle < ActiveRecord::Base
  attr_accessible :customer, :date, :plate
    def self.search(search)
		where("customer like '%#{search}%' or plate like '%#{search}%'")
	end
end

app/controllers/history_of_vehicles_controller.rb
class HistoryOfVehiclesController < ApplicationController

  def index
    #para rails 3.2.9 hasta 3.2.12(última versión a abril-2013)
      @history_of_vehicles = HistoryOfVehicle.search(params[:search]).page(params[:page]).per_page(5)
        respond_to do |format|
        format.html # index.html.erb
        format.xml { render :xml => @history_of_vehicles }
    end
  end

  def show
    @history_of_vehicle = HistoryOfVehicle.find(params[:id])
  end

  def new
    @history_of_vehicle = HistoryOfVehicle.new
  end

  def edit
    @history_of_vehicle = HistoryOfVehicle.find(params[:id])
  end

  def create
    @history_of_vehicle = HistoryOfVehicle.new(params[:history_of_vehicle])
    render :action => :new unless @history_of_vehicle.save
  end
 
  def update
    @history_of_vehicle = HistoryOfVehicle.find(params[:id])
    render :action => :edit unless @history_of_vehicle.update_attributes(params[:history_of_vehicle])
  end
 
  def destroy
    @history_of_vehicle = HistoryOfVehicle.find(params[:id])
    @history_of_vehicle.destroy
  end
end

app/helpers/history_of_vehicles_helper.rb
module HistoryOfVehiclesHelper
end

app/views/history_of_vehicles/_form.html.erb
<%= simple_form_for(@history_of_vehicle, :html => { :class => 'form-horizontal' }, :remote => true) do |f| %>

	<%= f.error_notification %>
	<%= display_base_errors @history_of_vehicle %>

  <%= f.input :plate %>
  <%= f.input :customer %>
  <%= f.input :date %>
	<div class="form-actions">
		<%= f.submit "guardar", :class => 'btn btn-primary' %>
		<%= link_to 'Atras', history_of_vehicles_path, :class => 'btn btn-small' %>
	</div>
<% end %>

app/views/history_of_vehicles/_history_of_vehicle.html.erb
<tr id=<%= "history_of_vehicle_#{history_of_vehicle.id}" %>>
<td><%= link_to history_of_vehicle.id, edit_history_of_vehicle_path(history_of_vehicle), :remote => true %></td>
<td><%= history_of_vehicle.plate %></td>
<td><%= history_of_vehicle.customer %></td>
<td><%= history_of_vehicle.date %></td>
<td>
<%= link_to image_tag('shows.png', :title  => "Mostrar Historial de vehiculos"), history_of_vehicle, :remote => true, :class => 'btn btn-mini' %>
<%= link_to image_tag('editar.png', :title  => "Editar Historial de vehiculos"),  edit_history_of_vehicle_path(history_of_vehicle), :remote => true,
:class => 'btn btn-mini' %>
<%= link_to image_tag('deletes.png', :title  => "Eliminar Historial de vehiculos"),  history_of_vehicle,
:data => { :confirm => 'Esta Seguro?' },
:method => :delete, :remote => true, :class => 'btn btn-mini btn-danger' %>
</td>
</tr>

app/views/history_of_vehicles/_show.html.erb
<%- model_class = HistoryOfVehicle -%>
<div class="page-header">
<h1>Historial De Vehiculo</h1>
</div>
<div class='history_of_vehicle'>
<p><b>Numero</b>: <%= @history_of_vehicle.id %></p>
<p><b>Placa</b>: <%= @history_of_vehicle.plate %></p>
<p><b>Cliente</b>: <%= @history_of_vehicle.customer %></p>
<p><b>Fecha</b>: <%= @history_of_vehicle.date %></p>
</div>

app/views/history_of_vehicles/create.js.erb
$('table tbody').append("<%= escape_javascript(render @history_of_vehicle) %>")
$.lazybox.close()

app/views/history_of_vehicles/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {niceClose: true});

app/views/history_of_vehicles/index.html.erb
<%- model_class = HistoryOfVehicle -%>
  <div class="page-header">
    <h1><u>Historial De Vehiculos</u><h1>
  </div>
<h3>Buscador Historial De Pago</h3>
<div class="navbar">
    <div class="navbar-inner">
    <i><li style="margin-top: 18px;" class="brand" href="#" >Buscar</li></i>
      <div class="row">
        <div class="span6">
           <%= form_tag request.path, :method => 'get' do %>
    <%= content_tag :label do %>
    <br>
    <%= text_field_tag :search, params[:search] , :id => "element" %>
        <%= submit_tag "Consultar", :name => nil, :class => "btn btn-primary", :style => "margin-top: -10px;" %>
        <% end %>
    <% end %>
        </div>
      </div>
    </div>
  </div>


<br />
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>#</th>
      <th>Placa</th>
      <th>Cliente</th>
      <th>Fecha</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <%= render @history_of_vehicles %> 
  </tbody>
<tfoot>
<tr>
<td><%= link_to image_tag('new.png', :title  => "Nuevo historial de vehiculos"),  new_history_of_vehicle_path, :remote => true %></td>
</tr>
</tfoot>
</table>
<br />
<br />
  <div align="center">
    <%= will_paginate @history_of_vehicles, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente&raquo;' %>
  </div>
  <tr>
    <td><b>Total Historial de vehiculos:</b></td>
      <td>
        <input type="text"  id="totalregs" class="span1" value="<%= @history_of_vehicles.total_entries %>" readonly />
     </td>
  </tr>

app/views/history_of_vehicles/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>");

app/views/history_of_vehicles/show.js.erb
$.lazybox("<%= j(render 'show') %>", {closeImg: true, klass: 'sticker', fixed: true})

app/views/history_of_vehicles/update.js.erb
$('tr#history_of_vehicle_<%= @history_of_vehicle.id %>').replaceWith("<%= escape_javascript(render @history_of_vehicle) %>")
$.lazybox.close()