config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do
  resources :cost_centers


  resources :cash_receipts


  resources :suppliers


  resources :spares


  resources :labors


  resources :work_orders


  resources :mechanicals


  resources :sale_by_cost_centers


  resources :form_of_payments


  resources :banks


  resources :shoppings


  resources :history_of_vehicles


  resources :account_receivables


  resources :account_payables


  resources :customers


  resources :profiles


  resources :documents


  authenticated :user do
    root :to => 'home#admin'
  end
  root :to => "home#index"
  devise_for :users
  resources :users

  

end

app/models/account_payable.rb
class AccountPayable < ActiveRecord::Base
  attr_accessible :from, :nit, :social_reason, :to
	def self.search(search)
		where("nit like '%#{search}%' or social_reason like '%#{search}%'")
	end
end

app/controllers/account_payables_controller.rb
class AccountPayablesController < ApplicationController

  def index
    #para rails 3.2.9 hasta 3.2.12(última versión a abril-2013)
      @account_payables = AccountPayable.search(params[:search]).page(params[:page]).per_page(5)
        respond_to do |format|
        format.html # index.html.erb
        format.xml { render :xml => @account_payables }
    end
  end

  def show
    @account_payable = AccountPayable.find(params[:id])
  end

  def new
    @account_payable = AccountPayable.new
  end

  def edit
    @account_payable = AccountPayable.find(params[:id])
  end

  def create
    @account_payable = AccountPayable.new(params[:account_payable])
    render :action => :new unless @account_payable.save
  end

  def update
    @account_payable = AccountPayable.find(params[:id])
    render :action => :edit unless @account_payable.update_attributes(params[:account_payable])
  end

  def destroy
    @account_payable = AccountPayable.find(params[:id])
    @account_payable.destroy
  end
end

app/helpers/account_payables_helper.rb
module AccountPayablesHelper
end

app/views/account_payables/_account_payable.html.erb
<tr id=<%= "account_payable_#{account_payable.id}" %>>
<td><%= link_to account_payable.id, edit_account_payable_path(account_payable), :remote => true %></td>
<td><%= account_payable.id %></td>
<td><%= account_payable.social_reason %></td>
<td><%= account_payable.nit %></td>
<td><%= account_payable.from %></td>
<td><%= account_payable.to %></td>
<td>
<%= link_to image_tag('shows.png', :title  => "Mostrar Cuenta"), account_payable, :remote => true, :class => 'btn btn-mini' %>
<%= link_to image_tag('editar.png', :title  => "Editar Cuenta"), edit_account_payable_path(account_payable), :remote => true,
:class => 'btn btn-mini' %>
<%= link_to image_tag('deletes.png', :title  => "Eliminar Cuenta"), account_payable,
:data => { :confirm => 'Esta Seguro?' },
:method => :delete, :remote => true, :class => 'btn btn-mini btn-danger' %>
</td>
</tr>

app/views/account_payables/_form.html.erb
<%= simple_form_for(@account_payable, :html => { :class => 'form-horizontal' }, :remote => true) do |f| %>

	<%= f.error_notification %>
	<%= display_base_errors @account_payable %>


  <%= f.input :social_reason %>
  <%= f.input :nit %>
  <%= f.input :from %>
  <%= f.input :to %>
<div class="form-actions">
	<%= f.submit "guardar", :class => 'btn btn-primary' %>
	<%= link_to 'Atras', account_payables_path, :class => 'btn btn-small' %>
</div>
<% end %>

app/views/account_payables/_show.html.erb
<%- model_class = AccountPayable -%>
<div class="page-header">
<h1>Cuenta por pagar</h1>
</div>
<div class='account_payable'>
<p><b>Numero</b>: <%= @account_payable.id %></p>
<p><b>razon social</b>: <%= @account_payable.social_reason %></p>
<p><b>nit</b>: <%= @account_payable.nit %></p>
<p><b>desde</b>: <%= @account_payable.from %></p>
<p><b>hasta</b>: <%= @account_payable.to %></p>
</div>

app/views/account_payables/create.js.erb
$('table tbody').append("<%= escape_javascript(render @account_payable) %>")
$.lazybox.close()

app/views/account_payables/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {niceClose: true});

app/views/account_payables/index.html.erb
<%- model_class = AccountPayable -%>
  <div class="page-header">
    <h1><u>Cuentas Por Pagar</u><h1>
  </div>
<h3>Buscador Cuentas Por Pagar</h3>
<div class="navbar">
    <div class="navbar-inner">
    <i><li style="margin-top: 18px;" class="brand" href="#" >Buscar</li></i>
      <div class="row">
        <div class="span6">
           <%= form_tag request.path, :method => 'get' do %>
    <%= content_tag :label do %>
    <br>
    <%= text_field_tag :search, params[:search] , :id => "element" %>
        <%= submit_tag "Consultar", :name => nil, :class => "btn btn-primary", :style => "margin-top: -10px;" %>
        <% end %>
    <% end %>
        </div>
      </div>
    </div>
  </div>


<br />
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>#</th>
      <th>Razon Social</th>
      <th>Nit</th>
      <th>Desde</th>
      <th>Hasta</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <%= render @account_payables %>
  </tbody>
  <tfoot>
    <tr>
      <td><%= link_to  image_tag('new.png', :title  => "Nuevo Documento"), new_account_payable_path, :remote => true %></td>
    </tr>
  </tfoot>
</table>
<br />
<br />
  <div align="center">
    <%= will_paginate @account_payables, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente&raquo;' %>
  </div>
  <tr>
    <td><b>Total Cuentas por pagar:</b></td>
      <td>
        <input type="text"  id="totalregs" class="span1" value="<%= @account_payables.total_entries %>" readonly />
     </td>
  </tr>

app/views/account_payables/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>");

app/views/account_payables/show.js.erb
$.lazybox("<%= j(render 'show') %>", {closeImg: true, klass: 'sticker', fixed: true})

app/views/account_payables/update.js.erb
$('tr#account_payable_<%= @account_payable.id %>').replaceWith("<%= escape_javascript(render @account_payable) %>")
$.lazybox.close()